### ISSUE TITLE
Segfault on debian buster

### ISSUE THREAD

**Issue by wolfsoft** [wolfsoft/libdcl#1]
Debian buster bug: dbp::process segfaults,

```
Reading symbols from /usr/local/bin/dbpager...(no debugging symbols found)...done.
[New LWP 393]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `dbpager test.dbpx'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5e5bf7afbf in dbp::process::process() () from /usr/local/lib/libdclbase.so.1
(gdb) bt
#0  0x00007f5e5bf7afbf in dbp::process::process() () from /usr/local/lib/libdclbase.so.1
#1  0x0000000000000043 in ?? ()
#2  0x000055b537aa18f4 in dbpager::tag_system::execute(dbpager::context&, std::ostream&, dbpager::tag const*) const ()
#3  0x00007f5e5c341eb6 in dbpager::tag_impl::execute(dbpager::context&, std::ostream&, dbpager::tag const*) const ()
   from /usr/local/lib/libdbpager.so.4
#4  0x000055b537a83ab6 in dbpager::dbpager_application::execute(dbpager::environment&, std::ostream&) const ()
#5  0x000055b537a75f49 in dbpager::console_application::on_execute() ()
#6  0x00007f5e5bf703f0 in dbp::application::run(int, char**) () from /usr/local/lib/libdclbase.so.1
#7  0x000055b537a73777 in main ()
```

**Comment by wolfsoft** [comment]
N.B. Did not reproduce in debian stretch and latest linux mint, hmm
